services:
  front:
    build: 
      context: .
      args:
        - HTTP_PROXY=${HTTP_PROXY} 
        - HTTPS_PROXY=${HTTPS_PROXY}
        - ALL_PROXY=${HTTP_PROXY}
    network_mode: host
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - ALL_PROXY=${HTTP_PROXY}
    restart: 'unless-stopped'
    container_name: yarabot_telegram_bot
    ports:
      - '2404:2404'
